#!/bin/sh

PATH=/var/bin:/bin:/usr/bin:/var/sbin:/sbin:/usr/sbin

create_node()
{
	device=$1

	rm -f /dev/${device}
	major=`awk "\\$2==\"$device\" {print \\$1}" /proc/devices`

	if [ ${major} ]; then
		echo Creating device node for $1
		mknod /dev/${device} c $major 0
	fi

}

create_node_dir()
{
	device=$1

	rm -rf /dev/${device}
	mkdir -p /dev/${device}

	major=`awk "\\$2==\"$device\" {print \\$1}" /proc/devices`

	if [ ${major} ]; then
		echo Creating device node for $1
		mknod /dev/${device}/0 c $major 0
	fi

}
